version: "3.9"

services:
  postgres:
    env_file:
      - .env
  webapp:
    env_file:
      - .env
  pgadmin:
    env_file:
      - .env
  nginx:
    build:
      dockerfile: Dockerfile.local
    env_file:
      - .env
