export const USER_START_FETCH_DATA = 'USER_START_FETCH_DATA';
export const USER_SUCCESS_FETCH_DATA = 'USER_SUCCESS_FETCH_DATA';
export const USER_FAILED_FETCH_DATA = 'USER_FAILED_FETCH_DATA';
export const USER_END_FETCH_DATA = 'USER_END_FETCH_DATA';
