export const LB_PENDING_FETCH_LIST_DATA = 'LB_PENDING_FETCH_LIST_DATA';
export const LB_SUCCESS_FETCH_LIST_DATA = 'LB_SUCCESS_FETCH_LIST_DATA';
export const LB_FAILED_FETCH_LIST_DATA = 'LB_FAILED_FETCH_LIST_DATA';
export const LB_FINISH_FETCH_LIST_DATA = 'LB_FINISH_FETCH_LIST_DATA';

