name: APP-CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy project to Yandex Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName 51.250.16.235
            User yura
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.CD_KEY }}

      - name: Stop the docker
        run: ssh staging 'cd defence-game && docker-compose down'

      - name: Pull new changes
        run: ssh staging 'cd defence-game && git checkout main && git pull origin'

      - name: Start the docker-container
        if: ${{ always() }}
        run: ssh staging 'cd defence-game && docker-compose up --build -d'
